Feature: Add Bluesky as a social media platform option
FlineDev/LinksKit pull request #5
Opened 2024-12-11 08:44 UTC by ChristianSko

Feature #

## Proposed Changes
  - Adds Bluesky as an option of social platform
 
@Jeehut Let me know if that looks good to you 😄

2024-12-11 12:30 UTC, Jeehut requested changes
@ChristianSko Thank you for adding Bluesky, I was gonna do it sometime, but didn't have the time yet!

I left a few comments, please take a look. Looks good overall though, nice little addition.

2024-12-11 12:30 UTC, Jeehut commented on Sources/LinksKit/Model/SocialPlatform.swift
> +   case bluesky
Can you please keep the list in alphabetic order? Same for when you switch-case over them down below. That makes this code easier to handle.

2024-12-11 12:30 UTC, Jeehut commented on Sources/LinksKit/Model/SocialPlatform.swift
> +      case .bluesky: URL(string: "https://app.bsky.cz/profile/\(handle)")!
Why `app.bsky.cz` which seems a Czech variant of the profile URL. I think we should go for `https://bsky.app/profile/\(handle)` here, no?

2024-12-11 13:10 UTC, ChristianSko commented on Sources/LinksKit/Model/SocialPlatform.swift
> +   case bluesky
Ah, makes sense; didn't realize that. Updated!

2024-12-11 13:14 UTC, ChristianSko commented on Sources/LinksKit/Model/SocialPlatform.swift
> +      case .bluesky: URL(string: "https://app.bsky.cz/profile/\(handle)")!
Good question! I'll actually have to look into that. I'm not sure why it's "cz." 
I'm also not located there. However, I tried it without "cz," and it just doesn't work. 🤔I think maybe it could be because Bluesky follows a similar approach to Mastodon, as it is also decentralized. 

Maybe its should be an instance? 

 It worked for me like this, but it raises the question of whether it's correct. I'll take a look later tonight and let you know!

2024-12-11 13:28 UTC, ChristianSko commented on Sources/LinksKit/Model/SocialPlatform.swift
> +      case .bluesky: URL(string: "https://app.bsky.cz/profile/\(handle)")!
Ignore my comment. I'm just gibberish 😆 It wasn't loading; now it is

2024-12-11 13:37 UTC, ChristianSko commented on Sources/LinksKit/Model/SocialPlatform.swift
> +      case .bluesky: URL(string: "https://app.bsky.cz/profile/\(handle)")!
Sorry, I sent something that didn't make sense. Ignore what I said above 🤦
 I had missed something... I've updated it as well!

2024-12-12 11:23 UTC, Jeehut approved these changes
Thank you very much! Looks good now. 💪  🎉

2024-12-12 11:23 UTC, merged